#pragma once

#define AssetCharacterAllowed(c)		( (c == L'_' || c == L'-') || (c >= 48 && ((c >= 97 && c <= 122 ) || (c <= 57 ) || (c >= 65 && c <= 90))) )

LPCWSTR g_lpszDiscordStatusCppBegin =
L"#include \"pch.h\"\n"
L"#include \"include/DiscordStatus.h\"\n"
L"#include \"include/Discord/RPC.h\"\n"
L"#include \"include/AlbumAssets.h\"\n\n"
L"HANDLE g_hAppDisabledEvent;\n"
L"static DiscordRichPresence g_DiscordRichPresence;\n"
L"static LPCSTR g_lpszCurrentAppID = NULL;\n\n"
L"static VOID UnicodeToMultiByte(LPCWSTR lpszUnicode, LPSTR *lppszMultibyte)\n"
L"{\n"
L"\tDWORD cbNeeded = WideCharToMultiByte( CP_UTF8, 0, lpszUnicode, -1, NULL, 0, NULL, NULL );\n"
L"\tif (cbNeeded == 0)\n"
L"\t{\n"
L"\t\t*lppszMultibyte = new CHAR[2];\n"
L"\t\t(*lppszMultibyte)[0] = ' ';\n"
L"\t\t(*lppszMultibyte)[1] = ' ';\n"
L"\t\treturn;\n"
L"\t}\n"
L"\t*lppszMultibyte = new CHAR[cbNeeded];\n"
L"\tWideCharToMultiByte(CP_UTF8, 0, lpszUnicode, -1, *lppszMultibyte, cbNeeded, NULL, NULL);\n"
L"}\n\n"
L"VOID UpdateDiscordStatus( LPDISCORDSTATUS lpStatus )\n"
L"{\n"
L"\tLPSTR Song		= NULL;\n"
L"\tLPSTR Artist	= NULL;\n"
L"\tLPSTR Album     = NULL;\n"
L"\tLPSTR AssetName = NULL;\n\n"
L"\tZeroMemory(&g_DiscordRichPresence, sizeof(g_DiscordRichPresence));\n\n"
L"\t/* NULL lpStatus means to clear the RPC status */\n"
L"\tif (lpStatus == NULL) {\n"
L"\t\tDiscord_ClearPresence();\n"
L"\t\treturn;\n"
L"\t}\n\n"
L"\tUnicodeToMultiByte( lpStatus->SongName, &Song );\n"
L"\tUnicodeToMultiByte( lpStatus->AlbumName, &Album );\n"
L"\tUnicodeToMultiByte( lpStatus->AlbumPath, &AssetName );\n"
L"\tUnicodeToMultiByte( lpStatus->Artist, &Artist );\n\n"
L"\tif (Song && Album && AssetName)\n"
L"\t{\n"
L"\t\tCHAR		szState[100]{};\n"
L"\t\tLPCSTR	lpszApplicationID;\n\n"
L"\t\tlpszApplicationID = NULL;\n\n"
L"\t\t/* Add album & artist into single string */\n"
L"\t\tStringCbPrintfA(szState, sizeof(szState), \"by %s on '%s'\", Artist, Album );\n\n"
L"\t\t/* Set the Discord RPC status info */\n"
L"\t\tg_DiscordRichPresence.startTimestamp	= lpStatus->Time;\n"
L"\t\tg_DiscordRichPresence.details         = Song;\n"
L"\t\tg_DiscordRichPresence.state           = szState;\n"
L"\t\tg_DiscordRichPresence.largeImageKey   = AssetName;\n"
L"\t\tg_DiscordRichPresence.largeImageText	= Album;\n\n"
L"\t\t//g_DiscordRichPresence.smallImageKey = SMALL_IMGKEY;\n\n"
L"\t\t/* Locate the application ID that contains the current album image */\n";

LPCWSTR g_lpszDiscordStatusCppEnd =
L"\n\t\t/* Album not found -- Set the application ID to any ID to force the default iTunes logo for the RPC image */\n"
L"\t\tif ( lpszApplicationID == NULL ) {\n"
L"\t\t\tlpszApplicationID = RPC_ASSET1_APPLICATION_ID;\n"
L"\t\t}\n\n"
L"\t\t/* Initialize Discord RPC for the application */\n"
L"\t\tif (g_lpszCurrentAppID != lpszApplicationID )\n"
L"\t\t{\n"
L"\t\t\tif ( g_lpszCurrentAppID != NULL ) {\n"
L"\t\t\t\tDiscord_Shutdown();\n"
L"\t\t\t}\n"
L"\t\t\tDiscord_Initialize(lpszApplicationID, NULL, 1, NULL);\n"
L"\t\t}\n\n"
L"\t\t/* Send the status */\n"
L"\t\tDiscord_UpdatePresence(&g_DiscordRichPresence);\n"
L"\t\tDiscord_RunCallbacks();\n\n"
L"\t\tg_lpszCurrentAppID = lpszApplicationID;\n"
L"\t}\n\n"
L"\t/* Cleanup */\n"
L"\tSAFE_STR_DELETE( Artist );\n"
L"\tSAFE_STR_DELETE( AssetName );\n"
L"\tSAFE_STR_DELETE( Album );\n"
L"\tSAFE_STR_DELETE( Song );\n"
L"}";